# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/intranet/software/avr-bettercopter/simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/intranet/software/avr-bettercopter/simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/intranet/software/avr-bettercopter/simulator/CMakeFiles /data/intranet/software/avr-bettercopter/simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/intranet/software/avr-bettercopter/simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quadcopter

# Build rule for target.
quadcopter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quadcopter
.PHONY : quadcopter

# fast build rule for target.
quadcopter/fast:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/build
.PHONY : quadcopter/fast

#=============================================================================
# Target rules for targets named irrlicht

# Build rule for target.
irrlicht: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 irrlicht
.PHONY : irrlicht

# fast build rule for target.
irrlicht/fast:
	$(MAKE) -f irrlicht/source/Irrlicht/CMakeFiles/irrlicht.dir/build.make irrlicht/source/Irrlicht/CMakeFiles/irrlicht.dir/build
.PHONY : irrlicht/fast

Application.o: Application.cpp.o
.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i
.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s
.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/Application.cpp.s
.PHONY : Application.cpp.s

CopterEntity.o: CopterEntity.cpp.o
.PHONY : CopterEntity.o

# target to build an object file
CopterEntity.cpp.o:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/CopterEntity.cpp.o
.PHONY : CopterEntity.cpp.o

CopterEntity.i: CopterEntity.cpp.i
.PHONY : CopterEntity.i

# target to preprocess a source file
CopterEntity.cpp.i:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/CopterEntity.cpp.i
.PHONY : CopterEntity.cpp.i

CopterEntity.s: CopterEntity.cpp.s
.PHONY : CopterEntity.s

# target to generate assembly for a file
CopterEntity.cpp.s:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/CopterEntity.cpp.s
.PHONY : CopterEntity.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/main.cpp.s
.PHONY : main.cpp.s

sim_kernel.o: sim_kernel.cpp.o
.PHONY : sim_kernel.o

# target to build an object file
sim_kernel.cpp.o:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/sim_kernel.cpp.o
.PHONY : sim_kernel.cpp.o

sim_kernel.i: sim_kernel.cpp.i
.PHONY : sim_kernel.i

# target to preprocess a source file
sim_kernel.cpp.i:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/sim_kernel.cpp.i
.PHONY : sim_kernel.cpp.i

sim_kernel.s: sim_kernel.cpp.s
.PHONY : sim_kernel.s

# target to generate assembly for a file
sim_kernel.cpp.s:
	$(MAKE) -f CMakeFiles/quadcopter.dir/build.make CMakeFiles/quadcopter.dir/sim_kernel.cpp.s
.PHONY : sim_kernel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... quadcopter"
	@echo "... rebuild_cache"
	@echo "... irrlicht"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
	@echo "... CopterEntity.o"
	@echo "... CopterEntity.i"
	@echo "... CopterEntity.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sim_kernel.o"
	@echo "... sim_kernel.i"
	@echo "... sim_kernel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

